feat: traduction implementation
Dogger-Inc/web-app pull request #16
Opened 2023-12-13 19:59 UTC by KizutoFR

Bouton temporaire pour tester le bon changement de langue (donc style à revoir et à intégrer à la navbar plutôt.

2023-12-13 20:47 UTC, Oui-Dev requested changes
Maybe faire un dossier par locale au lieu d'un fichier
et comme ça on fait un fichier par gros block (ou pas par page) pour éviter de se retrouver avec un seul fichier qui va faire 9999999 lignes

2023-12-13 20:47 UTC, Oui-Dev commented on resources/js/Components/Items/LangageSelector.vue
je pense que le fichier est pas au bon endroit (il doit pas etre dans "Items" ça n'a rien a voir)

2023-12-13 20:47 UTC, Oui-Dev commented on resources/js/Components/Items/LangageSelector.vue
> +const lang = [{name: 'Français', value: 'fr'},{name: 'English', value: 'en'},{name: 'Deutsch', value: 'de'},{name: '中文', value: 'zh'},{name: 'Русский', value: 'ru'}]
maybe mieux indenter pour eviter le inline et mettre au pluriel la variable ?

2023-12-13 20:47 UTC, Oui-Dev commented on resources/js/Pages/Public/Index.vue
> +import LangageSelector from '../../Components/Items/LangageSelector.vue';
utiliser les alias pour les import '@/Components/....

2024-01-05 15:12 UTC, oltean-petru requested changes
Fait gaffe, certain fichier sont en indentanion 2 au lieu de 4 et pense aussi a faire un dossier par locale (comme Kevin a propose). ca sera mieux pour gerer les differents interfaces.

2024-01-24 09:03 UTC, Oui-Dev approved these changes

2024-01-24 09:04 UTC, merged