Feature/projects
Dogger-Inc/web-app pull request #19
Opened 2024-01-24 10:43 UTC by lucasboinet

2024-03-07 08:38 UTC, oltean-petru commented
![image](https://github.com/Dogger-Inc/web-app/assets/70693810/78c01a74-2afe-4ce5-af3a-b71ed61ed93b)

- [ ] Pull main and resolve conflicts
- [ ] Add "back to issues" button
- [ ] Remove "null" tag (if no error code)
- [ ] Redesign title to better display long errors

2024-03-07 09:18 UTC, Oui-Dev requested changes

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Projects/List.vue
> +    console.log(form)
petit console.log qui traine

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Projects/List.vue
> +const searchByOpts = [{ name: t('projects.name'), key: 'name' }];
en soit la variable sert a rien nan ? tu peux passer l'array direct en props ?

2024-03-07 09:18 UTC, Oui-Dev commented on app/Http/Controllers/ProjectsController.php
> +            'key' => strtoupper(Str::random(8)),
on ferrai pas une clé un peu plus complexe pour les projets ?

2024-03-07 09:18 UTC, Oui-Dev commented on app/Models/Issue.php
> +        return $this->belongsTo(Project::class, 'project_id');
ta eu des soucis pour que tu spécifie la clé ? normalement si tu suis la convention de nommage laravel detecte auto la clé

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Companies/Details.vue
> +import TabUsers from '@/Components/Tabs/TabUsers.vue';
ça pour le coup j'avoue je sais pas c'est quoi le mieux, car en vrai il peut y avoir plein de TabDetails différent par exemple donc jspa si tous les mettre dans le dossier components c'est bien (en vrai jspa du tout)

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Issues/Details.vue
> +import List from '../../../Components/Items/List.vue';
utilise l'alias

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Issues/Details.vue
> +    }
si jamais le current user tu peux le recup dans les global props (voir HandleInertiaRequest.php) en utilisant UsePage de inertia

après j'ai vu que dans le controller tu lui assignais des proriété en plus donc maybe ta pas le choix (par contre si tu utilise ces propriété en plus a plusieurs endroit maybe, ce serait bien de faire un attribut et de l'append dans handleInertiaRequest) si tu veux on pourra en parler ensemble si tu comprend pas trop ce que je veux dire

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Issues/List.vue
> +const searchByOpts = [{ name: 'Message', key: 'message' }];
en soit la variable sert a rien nan ? tu peux passer l'array direct en props ?

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Issues/List.vue
> +            @selected-item="(value) => console.log(value)"
console.log ?

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Issues/List.vue
> +            <slot name="listItem" :item="item.item" />
pq un slot ? met l'html que tu veux display ici

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Projects/List.vue
> +    company_id: undefined,
si je dis pas de connerie pour éviter de la valeur disparait au moment du submit de la requete, et donc que ton validator pense que la valeur est absente de la requete, met une string vide (derriere laravel compte ça comme une valeur null)
je sais que je met tjr une string vide perso, après si ça marche comme ça laisse

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Projects/List.vue
> +        },
si tu veux gagner 2 ligne tu peux faire direct onStart: () => formJoin.clearErrors(),

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Projects/Partials/TabDetails.vue
> +import { watch } from 'vue';
{ ref, watch }

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Projects/Partials/TabDetails.vue
> +    name: undefined,
du coup la pareil perso j'aurai mis string vide mais si ça marche laisse comme ça

2024-03-07 09:18 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Projects/Partials/TabDetails.vue
> +        }
ça marche ça ? parce que la tu réassigne une constante donc pour moi ta une erreur 

ps : tu peux direct assign props.project.id et props.project.name quand tu declare ton useForm

2024-03-27 08:37 UTC, lucasboinet commented on resources/js/Pages/Dashboard/Projects/List.vue
> +        },
bien vu

2024-03-27 08:38 UTC, lucasboinet commented on resources/js/Pages/Dashboard/Projects/Partials/TabDetails.vue
> +        }
c'est pas une constante justement :D

2024-03-27 10:09 UTC, Oui-Dev approved these changes

2024-03-27 10:09 UTC, merged