Feature/issue messages
Dogger-Inc/web-app pull request #37
Opened 2024-03-27 14:20 UTC by lucasboinet

2024-03-27 14:50 UTC, Oui-Dev requested changes
Pour l'edit j'aurai fait plus simple je pense que t'es cassé un peu la tete
En gros j'aurai fait un seul form avec du coup le comment_id et en gros derriere pour savoir si je post sur edit ou sur add bah je check si comment_id est nul ou pas

Et perso j'aurai mis les commentaire dans un tab a part et pas dans le tab des détails

2024-03-27 14:50 UTC, Oui-Dev commented on app/Http/Controllers/IssuesController.php
> +        }
tu peux faire direct ->with(['user', 'replyTo']) avant ton orderBy normalement ce qui va éviter le foreach

2024-03-27 14:50 UTC, Oui-Dev commented on app/Http/Controllers/IssuesController.php
> +            'reply_to' => ['nullable', 'integer'],
rajoute un Rule::exist('users', 'id') pour éviter de tenter de save un id qui n'existe pas
verifie la syntax mais c'est un truc du genre

2024-03-27 14:50 UTC, Oui-Dev commented on app/Http/Controllers/IssuesController.php
> +            'commentable_id' => $issue->id,
ta pas besoin de fill les champs la normalement ils seront fill direct avec la ligne d'après (a check)

2024-03-27 14:50 UTC, Oui-Dev commented on app/Http/Controllers/IssuesController.php
> +    }
passe direct comme ça editComment(Comment $comment) en soit tu n'a pas besoin de l'issue dans ce cas
et maybe faire un CommentController ? jspa trop

2024-03-27 14:50 UTC, Oui-Dev commented on app/Models/Comment.php
> +        'commentable_id'
c'est pas fillable ça, c'est auto fill par laravel

2024-03-27 14:50 UTC, Oui-Dev commented on resources/js/Components/CommentsThread.vue
> +    },
ça get le direct dans le compo via UsePage t'embete pas a le passer en props

2024-03-27 14:50 UTC, Oui-Dev commented on resources/js/Components/CommentsThread.vue
> +    },
du coup si on fait un CommentController pour l'edit ce serait tjr le meme path et pas obliger d'avoir ce props

2024-03-27 14:52 UTC, oltean-petru commented
manque le avatar (initials)
![image](https://github.com/Dogger-Inc/web-app/assets/70693810/f9de713c-a841-41cf-a7fd-04827c11a729)

on ne peut pas envoyer des messages relativement longues 
![image](https://github.com/Dogger-Inc/web-app/assets/70693810/529d6c9f-4cfe-419d-ad33-1ca656aa1d73)
![image](https://github.com/Dogger-Inc/web-app/assets/70693810/60e774c3-af8a-4e5b-a73e-1f9e619fcf27)

2024-03-27 15:20 UTC, lucasboinet commented on app/Http/Controllers/IssuesController.php
> +            'commentable_id' => $issue->id,
je les ai mis pcqe justement il les fill pas tout seul j'avais une erreur

2024-03-27 15:37 UTC, lucasboinet commented on app/Models/Comment.php
> +        'commentable_id'
justement je crois pas la j'avais une erreur quand je le mettais pas :/

2024-03-28 09:10 UTC, oltean-petru commented
![image](https://github.com/Dogger-Inc/web-app/assets/70693810/f7fa59e4-c065-427e-a2a2-5fe196827d94)
probleme de message longue toujour presente

2024-04-17 08:12 UTC, Oui-Dev approved these changes

2024-04-17 08:12 UTC, merged