feat: Performances view & users assignment to performances and issues
Dogger-Inc/web-app pull request #43
Opened 2024-04-17 13:29 UTC by lucasboinet

2024-04-17 13:30 UTC, lucasboinet commented
#32

2024-04-17 13:31 UTC, lucasboinet commented
#39

2024-04-28 15:58 UTC, Oui-Dev requested changes
quelques petites trucs niveau code
je laisse @oltean-petru faire sa review fonctionnel

2024-04-28 15:58 UTC, Oui-Dev commented on database/migrations/2024_04_17_112105_update_performance_table.php
> +        //
oublie du down ici

2024-04-28 15:58 UTC, Oui-Dev commented on app/Models/Performance.php
> -
tu ne met pas la relation vers le group a la place ?

2024-04-28 15:58 UTC, Oui-Dev commented on resources/js/Components/Form/UsersSearch.vue
> +})
je ne sais pas si c'est exactement ce que tu cherche mais si derriere tu veux pouvoir faire un v-model sur ton composant tu peux utiliser ça https://vuejs.org/api/sfc-script-setup.html#definemodel

mais je crois pas que ce soit adapté a ton cas la

2024-04-28 15:58 UTC, Oui-Dev commented on resources/js/Components/Form/UsersSearch.vue
> +            <div
c'est un détail mais vu que c'est une liste si j'ai bien compris
ce serait pas déconnant de faire des `<ul>` `<li>` nan ?

2024-04-28 15:58 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Issues/Details.vue
> +}
soit tu peux utiliser un form commun, soit tu peux import `router` au lieu de `useForm` et tu fait un `router.post(route(...), {user_id: user.id}, {onStart: ...}`

d'ailleurs si tu fait rien dans le onSuccess pas obligé de le mettre 😅

2024-04-28 15:58 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Performances/Details.vue
> +}
pareil ici du coup

2024-04-28 15:58 UTC, Oui-Dev commented on routes/web.php
> +        Route::post('/{issue}/unassign', 'unassignUser')->name('unassignUser.post');
j'ai pour habitude de faire kebab-case et non du camelCase pour les routes name (après je ne sais lequel est la convention en laravel)

2024-04-29 12:13 UTC, oltean-petru reviewed
visually ok

2024-04-29 12:13 UTC, oltean-petru approved these changes

2024-04-29 16:06 UTC, lucasboinet commented on app/Models/Performance.php
> -
ah si ouais je peux faire ca

2024-04-29 16:08 UTC, lucasboinet commented on resources/js/Components/Form/UsersSearch.vue
> +})
ouais nan du tout moi je veux pas faire de v-model

2024-04-29 16:22 UTC, lucasboinet commented on routes/web.php
> +        Route::post('/{issue}/unassign', 'unassignUser')->name('unassignUser.post');
ca à l'air d'être plus du camelCase la convention de ce que je vois sur internet

2024-04-29 17:25 UTC, Oui-Dev requested changes
2 petites erreurs d'étourderie et on est good

2024-04-29 17:25 UTC, Oui-Dev commented on database/migrations/2024_04_17_112105_update_performance_table.php
> +            $table->timestamps();
je ne vois pas ce que ça fait la 😅 (vis a vis de la modif d'au dessus)
et il manque la modif de "duration"

2024-04-29 17:25 UTC, Oui-Dev commented on resources/js/Pages/Dashboard/Performances/Details.vue
> +}
ça a pas été modif ici

2024-04-29 20:32 UTC, Oui-Dev approved these changes

2024-04-29 20:32 UTC, merged